soil_mapping = {
    'surface_soil_heat_flux_1': {'name': 'G_1_1_1', 'units': 'W m-2'},
    'surface_soil_heat_flux_2': {'name': 'G_2_1_1', 'units': 'W m-2'},
    'surface_soil_heat_flux_3': {'name': 'G_3_1_1', 'units': 'W m-2'},
    'vwc_1': {'name': 'SWC_1_1_1', 'units': '%'},
    'vwc_2': {'name': 'SWC_2_1_1', 'units': '%'},
    'vwc_3': {'name': 'SWC_3_1_1', 'units': '%'},
    'vwc_4': {'name': 'SWC_4_1_1', 'units': '%'},
    'vwc_5': {'name': 'SWC_5_1_1', 'units': '%'},
    'vwc_6': {'name': 'SWC_6_1_1', 'units': '%'},
    'vwc_7': {'name': 'SWC_7_1_1', 'units': '%'},
    'vwc_8': {'name': 'SWC_8_1_1', 'units': '%'},
    'vwc_9': {'name': 'SWC_9_1_1', 'units': '%'},
    'vwc_10': {'name': 'SWC_10_1_1', 'units': '%'},
    'vwc_11': {'name': 'SWC_11_1_1', 'units': '%'},
    'vwc_12': {'name': 'SWC_12_1_1', 'units': '%'},
    'soil_temp_1': {'name': 'TS_1_1_1', 'units': 'deg C'},
    'soil_temp_2': {'name': 'TS_2_1_1', 'units': 'deg C'},
    'soil_temp_3': {'name': 'TS_3_1_1', 'units': 'deg C'},
    'soil_temperature_west': {'name': 'TS', 'units': 'deg C'},
    'soil_temperature_east': {'name': 'TS', 'units': 'deg C'},
    'soil_temperature_south': {'name': 'TS', 'units': 'deg C'},
    'temp_1': {'name': 'TS', 'units': 'deg C'},
}
